language: c
compiler: gcc

install:
  - sudo pip install cpplint

script: 
  - cpplint --filter=-whitespace/braces,-build/include_subdir,-whitespace/newline,-whitespace/line_length ./Lesson*/app/main.c  

after_success:
  - echo "Success"
  
after_failure:
  - cat oclint.log
